//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelasWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public string Cue { get; set; }
        public string Anexo { get; set; }
        public string Cue_Anexo { get; set; }
        public string CursoDivisionId { get; set; }
        public string Curso { get; set; }
        public string Division { get; set; }
        public string Sexo { get; set; }
        public string FechaNac { get; set; }
        public int Id { get; set; }
    }
}
